# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b4c416bef54dfd984f70c021cc23aa499075d0cee1a7ae37e65744de4d9f60174f6a6dd498af1a6881fdf291ced4fb844f902e051290a18296f41e039c1ae5

test:
  secret_key_base: 74ad76dbaee1b94fdac0c94818555c93bb3148fa7d9e0cdf19be4d996c5091708e0b6935afb6373d0fd03333c9d0608dfea009b252d6773a71abfe233ecf93e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
